stages:
  - build
  - release

variables:
  IMAGE_RELEASE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  IMAGE_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

docker:build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG == null'
  image: docker
  services:
      - docker:dind
  script:
    - docker build -t $IMAGE_COMMIT .

docker:build-push:
  stage: release
  image: docker
  rules:
    - if: '$CI_COMMIT_TAG != null'
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE_RELEASE -t $IMAGE_LATEST .
    - docker push $IMAGE_RELEASE
    - docker push $IMAGE_LATEST
